### ISSUE TITLE
Feature Request: Cloudflare Access-related Metrics

### ISSUE THREAD

**Issue by wolfmd** [ricardbejarano/cloudflare_exporter#1]
Hey there! 

I'm curious if this project would be open to pull requests that add support for exporting Cloudflare Access related metrics. The main objective is to have the expiration time of Access service tokens exported but I figure I might as well add some other useful metrics around count of SSO logins and whatnot while I'm there. I'm open to putting these metrics behind a flag since I know not everyone purchases Access.

Thanks and Happy New Year! 
Michael

**Comment by ricardbejarano** [comment]
Go ahead please!

Not sure [the official Cloudflare API client library](https://pkg.go.dev/github.com/cloudflare/cloudflare-go) supports it, but go ahead!

Remember to prefix metrics for access as `cloudflare_access_*`.

Happy new year to you too!

**Comment by ricardbejarano** [comment]
Being dealt with in #3, closing issue.
