### ISSUE TITLE
Is there have grafana dashboard for this exporter?

### ISSUE THREAD

**Issue by iamkcyao** [ricardbejarano/cloudflare_exporter#4]
I got the cloudflare metrics, but I need to Visulation,
Is there have grafana dashboard for this exporter?

**Comment by ricardbejarano** [comment]
A Grafana dashboard is definetly something that is on the project's to-do list.

At this very moment, **no, there is no Grafana dashboard right now**, but I've dome some testing with the metrics in a Grafana instance of my own, and stuff like the distribution by country with the WorldMap plugin works flawlessly.

I will **push this higher within my priorities** but cannot give you the results right now.
Needless to say you're more than welcome to contribute, if you will.

Leaving this open as we work towards having a premade Grafana dashboard.

**Comment by ricardbejarano** [comment]
I've written [ricardbejarano/graphql_exporter](https://github.com/ricardbejarano/graphql_exporter) to replace this exporter with Cloudflare's GraphQL Analytics API.

See [examples/cloudflare_analytics_api.md](https://github.com/ricardbejarano/graphql_exporter/blob/master/examples/cloudflare_analytics_api.md) to learn how to use it.

Given that this is way outside `graphql_exporter`'s scope this issue won't be ported over to it. Returned metrics heavily rely upon the queries you made, therefore there's no way to provide a cookie-cutter dashboard for everyone to use.
